language: objective-c
osx_image: xcode7.1
xcode_workspace: Crust.xcworkspace
xcode_scheme: Crust
xcode_sdk: iphonesimulator9.1
script:
 - xcodebuild -workspace Crust.xcworkspace -scheme Crust -sdk iphonesimulator build test
