language: objective-c
osx_image: xcode8.2
xcode_workspace: Crust.xcworkspace
xcode_scheme: Crust
xcode_sdk: iphonesimulator10.2
script:
 - set -o pipefail
 - xcodebuild -version
 - xcodebuild -showsdks
 - xcodebuild -workspace Crust.xcworkspace -scheme Crust -sdk iphonesimulator -destination "OS=10.2,name=iPhone 7" ONLY_ACTIVE_ARCH=NO build test
