language: objective-c
osx_image: xcode8.1
xcode_workspace: Crust.xcworkspace
xcode_scheme: Crust
xcode_sdk: iphonesimulator10.0
script:
 - set -o pipefail
 - xcodebuild -version
 - xcodebuild -showsdks
 - xcodebuild -workspace Crust.xcworkspace -scheme Crust -sdk iphonesimulator -destination "OS=10.1,name=iPhone 7 Plus" ONLY_ACTIVE_ARCH=NO build test
